version: 1.0
provider:
  name: openfaas
  gateway: http://34.132.7.177:8080
functions:
  register-user:
    lang: python3
    handler: ./register-user
    image: mspawanranjith/register-user:latest

  register-user-with-id:
    lang: python3
    handler: ./register-user-with-id
    image: mspawanranjith/register-user-with-id:latest

  get-user-id:
    lang: python3
    handler: ./get-user-id
    image: mspawanranjith/get-user-id:latest

  user-service-login:
    lang: python3
    handler: ./user-service-login
    image: mspawanranjith/user-service-login:latest

  social-graph-insert-user:
    lang: python3
    handler: ./social-graph-insert-user
    image: mspawanranjith/social-graph-insert-user:latest

  social-graph-follow:
    lang: python3
    handler: ./social-graph-follow
    image: mspawanranjith/social-graph-follow:latest

  social-graph-get-followers:
    lang: python3
    handler: ./social-graph-get-followers
    image: mspawanranjith/social-graph-get-followers:latest

  social-graph-get-followees:
    lang: python3
    handler: ./social-graph-get-followees
    image: mspawanranjith/social-graph-get-followees:latest

  social-graph-unfollow:
    lang: python3
    handler: ./social-graph-unfollow
    image: mspawanranjith/social-graph-unfollow:latest

  social-graph-unfollow-with-username:
    lang: python3
    handler: ./social-graph-unfollow-with-username
    image: mspawanranjith/social-graph-unfollow-with-username:latest

  social-graph-follow-with-username:
    lang: python3
    handler: ./social-graph-follow-with-username
    image: mspawanranjith/social-graph-follow-with-username:latest

  media-front-upload-media:
    lang: dockerfile
    handler: ./media-front-upload-media
    image: mspawanranjith/media-front-upload-media:latest
    environment:
        BLOB_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=davidhliu2020sfaas;AccountKey=dNrgfTFfCcINupXC0tnLaDxmkVeFnQhq0cFn8UO+WwOlzYiyLuZSY6bwSmAt4TkehFCkFBuNLgDvTAEBVERPKQ==;EndpointSuffix=core.windows.net"
        CONTAINER_NAME: "deathstar-media"

  compose-post-frontend:
    lang: python3
    handler: ./compose-post-frontend
    image: mspawanranjith/compose-post-frontend:latest
    environment:
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  user-service-upload-creator-with-user-id:
    lang: python3
    handler: ./user-service-upload-creator-with-user-id
    image: mspawanranjith/user-service-upload-creator-with-user-id:latest
    environment:
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  unique-id-service-upload-unique-id:
    lang: python3
    handler: ./unique-id-service-upload-unique-id
    image: mspawanranjith/unique-id-service-upload-unique-id:latest
    environment:
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  media-service-upload-media:
    lang: python3
    handler: ./media-service-upload-media
    image: mspawanranjith/media-service-upload-media:latest
    environment:
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  text-service-upload-text:
    lang: python3
    handler: ./text-service-upload-text
    image: mspawanranjith/text-service-upload-text:latest
    environment:
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  url-shorten-service-upload-urls:
    lang: python3
    handler: ./url-shorten-service-upload-urls
    image: mspawanranjith/url-shorten-service-upload-urls:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  user-mention-service-upload-user-mentions:
    lang: python3
    handler: ./user-mention-service-upload-user-mentions
    image: mspawanranjith/user-mention-service-upload-user-mentions:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s


  compose-post-service-upload-creator:
    lang: python3
    handler: ./compose-post-service-upload-creator
    image: mspawanranjith/compose-post-service-upload-creator:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  compose-post-service-upload-unique-id:
    lang: python3
    handler: ./compose-post-service-upload-unique-id
    image: mspawanranjith/compose-post-service-upload-unique-id:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s


  compose-post-service-upload-media:
    lang: python3
    handler: ./compose-post-service-upload-media
    image: mspawanranjith/compose-post-service-upload-media:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s


  compose-post-service-upload-urls:
    lang: python3
    handler: ./compose-post-service-upload-urls
    image: mspawanranjith/compose-post-service-upload-urls:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s


  compose-post-service-upload-user-mentions:
    lang: python3
    handler: ./compose-post-service-upload-user-mentions
    image: mspawanranjith/compose-post-service-upload-user-mentions:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  compose-post-service-upload-text:
    lang: python3
    handler: ./compose-post-service-upload-text
    image: mspawanranjith/compose-post-service-upload-text:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  compose-post-service-compose-and-upload:
    lang: python3
    handler: ./compose-post-service-compose-and-upload
    image: mspawanranjith/compose-post-service-compose-and-upload:latest
    environment:
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  post-storage-service-store-post:
    lang: python3
    handler: ./post-storage-service-store-post
    image: mspawanranjith/post-storage-service-store-post:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  post-storage-service-read-posts:
    lang: python3
    handler: ./post-storage-service-read-posts
    image: mspawanranjith/post-storage-service-read-posts:latests
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  user-timeline-service-write-user-timeline:
    lang: python3
    handler: ./user-timeline-service-write-user-timeline
    image: mspawanranjith/user-timeline-service-write-user-timeline:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  user-timeline-service-read-user-timeline:
    lang: python3
    handler: ./user-timeline-service-read-user-timeline
    image: mspawanranjith/user-timeline-service-read-user-timeline:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"
        REDIS_SERVER: "ds-redis-8bdf494b9-9w4bx"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6
        read_timeout: 20s
        write_timeout: 20s
        exec_timeout: 20s

  user-timeline-read-frontend:
    lang: python3
    handler: ./user-timeline-read-frontend
    image: mspawanranjith/user-timeline-read-frontend:latest

  ds-net:
    lang: dockerfile
    handler: ./ds-net
    image: mspawanranjith/ds-net

