apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ds-redis
spec:
  selector:
    matchLabels:
      app: ds-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: ds-redis
    spec:
      containers:
      - name: ds-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
          name: redis